Fix inconsistent enum name in bindings generator
Example: when using godot-rust with the VoxelTools engine module, the api.json has many nested 'Result' types.
In some occurrences, these identifiers are prefixed with the containing class, e.g. VoxelStreamResult.
However, some references to these type names are not using the prefixed identifier, thus creating compile errors:

---------------------------------------------------------------------------------------------------------------------------------------------------------
error[E0425]: cannot find function, tuple struct or tuple variant `Result` in module `crate::generated::voxel_stream`
    --> <path>/target/<toolchain>/debug/build/gdnative-bindings-6c3842bd5f0b6d58/out/generated.rs:3963:2992
     |
3963 | ... ; crate :: generated :: voxel_stream :: Result (ret) } } # [doc = ""] # [doc = ""] # [inline] pub fn get_block_size (& self) -> Vecto...
     |                                             ^^^^^^ not found in `crate::generated::voxel_stream`
---------------------------------------------------------------------------------------------------------------------------------------------------------